name: opc
version: '${project.version}'
main: me.opkarol.opc.OpC
api-version: 1.19
authors: [ ThisOpKarol ]
description: OpC is a modern and blazing ly fast spigot api extension which allows developers to do tasks quicker and replace boring tasks with new things.
softdepend:
  - PlaceholderAPI
  - Vault